export const customersMap = {
  "id": "id",
  "Customer ID": "uuid",
  "Customer Number": "customerNumber",
  "Special Account Number": "specialAccountNumber",
  "Is Company": "isCompany",
  "Is Third Party": "isThirdParty",
  "Name": "name",
  "First Name": "firstName",
  "Last Name": "lastName",
  "Contact Name": "contactName",
  "Tax Registration Number": "taxRegistrationNumber",
  "Phone": "phone",
  "Fax": "fax",
  "Mobile": "mobile",
  "Email": "email",
  "Marketing Email/SMS disabled": "marketingDisabled",
  "Price Level": "priceLevel",
  "Terms": "terms",
  "Default Discount (Percentage)": "defaultDiscount",
  "Address": "address",
  "Suburb": "suburb",
  "State": "state",
  "Postcode": "postcode",
  "Country": "country",
  "Street Address": "streetAddress",
  "Street Address Suburb": "streetSuburb",
  "Street Address State": "streetState",
  "Street Address Postcode": "streetPostcode",
  "Note": "note",
  "Tags": "tags",
  "Source Of Business": "sourceOfBusiness",
  "Running Balance": "runningBalance",
  "Finalized Balance": "finalizedBalance",
  "Creditor": "creditor",
  "Created At": "createdAt",
  "Last Invoice Date": "lastInvoiceDate"
}

export const vehiclesMap = {
  "id": "id",
  "Vehicle Number": "vehicleNumber",
  "Registration Number": "registrationNumber",
  "Location": "location",
  "Fleet Number": "fleetNumber",
  "Driver Name": "driverName",
  "Driver Phone": "driverPhone",
  "Driver Email": "driverEmail",
  "Make": "make",
  "Model": "model",
  "Year": "year",
  "VIN": "vin",
  "Color": "color",
  "Body Type": "bodyType",
  "Service Interval": "serviceInterval",
  "Transmission Type": "transmissionType",
  "Battery": "battery",
  "Odometer": "Odometer",
  "Engine": "Engine",
  "Engine Type": "engineType",
  "Engine Oil Type": "engineOilType",
  "Engine Oil Quantity": "engineOilQuality",
  "Power Steering Oil Type": "powerSteeringOilType",
  "Power Steering Oil Quantity": "powerSteeringOilQuantity",
  "Transmission Oil Type": "transmissionOilType",
  "Transmission Oil Quantity": "transmissionOilQuantity",
  "Transfer Case Oil Type": "transferCaseOilType",
  "Transfer Case Oil Quantity": "transferCaseOilQuantity",
  "Coolant Type": "coolantType",
  "Coolant Quantity": "coolantQuantity",
  "Fuel Type": "fuelType",
  "Air Filter": "airFilter",
  "Oil Filter": "oilFilter",
  "Fuel Filter": "fuelFilter",
  "Transmission Filter": "transmissionFilter",
  "Hydraulic Filter": "hydraulicFilter",
  "Tyre Size": "tyreSize",
  "Created At": "createdAt"
}