export const customersMap = {
  "id": "id",
  "Customer ID": "uuid",
  "Customer Number": "customerNumber",
  "Special Account Number": "specialAccountNumber",
  "Is Company": "isCompany",
  "Is Third Party": "isThirdParty",
  "Name": "name",
  "First Name": "firstName",
  "Last Name": "lastName",
  "Contact Name": "contactName",
  "Tax Registration Number": "taxRegistrationNumber",
  "Phone": "phone",
  "Fax": "fax",
  "Mobile": "mobile",
  "Email": "email",
  "Marketing Email/SMS disabled": "marketingDisabled",
  "Price Level": "priceLevel",
  "Terms": "terms",
  "Default Discount (Percentage)": "defaultDiscount",
  "Address": "address",
  "Suburb": "suburb",
  "State": "state",
  "Postcode": "postcode",
  "Country": "country",
  "Street Address": "streetAddress",
  "Street Address Suburb": "streetSuburb",
  "Street Address State": "streetState",
  "Street Address Postcode": "streetPostcode",
  "Note": "note",
  "Tags": "tags",
  "Source Of Business": "sourceOfBusiness",
  "Running Balance": "runningBalance",
  "Finalized Balance": "finalizedBalance",
  "Creditor": "creditor",
  "Created At": "createdAt",
  "Last Invoice Date": "lastInvoiceDate"
}

export const vehiclesMap = {
  "id": "id",
  "Vehicle Number": "vehicleNumber",
  "Registration Number": "registrationNumber",
  "Location": "location",
  "Fleet Number": "fleetNumber",
  "Driver Name": "driverName",
  "Driver Phone": "driverPhone",
  "Driver Email": "driverEmail",
  "Make": "make",
  "Model": "model",
  "Year": "year",
  "VIN": "vin",
  "Color": "color",
  "Body Type": "bodyType",
  "Service Interval": "serviceInterval",
  "Transmission Type": "transmissionType",
  "Battery": "battery",
  "Odometer": "Odometer",
  "Engine": "Engine",
  "Engine Type": "engineType",
  "Engine Oil Type": "engineOilType",
  "Engine Oil Quantity": "engineOilQuality",
  "Power Steering Oil Type": "powerSteeringOilType",
  "Power Steering Oil Quantity": "powerSteeringOilQuantity",
  "Transmission Oil Type": "transmissionOilType",
  "Transmission Oil Quantity": "transmissionOilQuantity",
  "Transfer Case Oil Type": "transferCaseOilType",
  "Transfer Case Oil Quantity": "transferCaseOilQuantity",
  "Coolant Type": "coolantType",
  "Coolant Quantity": "coolantQuantity",
  "Fuel Type": "fuelType",
  "Air Filter": "airFilter",
  "Oil Filter": "oilFilter",
  "Fuel Filter": "fuelFilter",
  "Transmission Filter": "transmissionFilter",
  "Hydraulic Filter": "hydraulicFilter",
  "Tyre Size": "tyreSize",
  "Created At": "createdAt"
}

export const jobTypes = [
  { key: "Air Conditioning", label: "Air Conditioning" },
  { key: "Auto Electrical", label: "Auto Electrical" },
  { key: "Battery", label: "Battery" },
  { key: "belts", label: "belts" },
  { key: "Brake Systems", label: "Brake Systems" },
  { key: "Callout", label: "Callout" },
  { key: "Clutch & Transmission", label: "Clutch & Transmission" },
  { key: "consuambles", label: "consuambles" },
  { key: "Cooling Systems", label: "Cooling Systems" },
  { key: "Customer Order", label: "Customer Order" },
  { key: "Exhaust Systems", label: "Exhaust Systems" },
  { key: "Fit 2nd hand tyres", label: "Fit 2nd hand tyres" },
  { key: "Fitting", label: "Fitting" },
  { key: "Freight", label: "Freight" },
  { key: "Log book Service", label: "Log book Service" },
  { key: "Major Service", label: "Major Service" },
  { key: "Mechanical", label: "Mechanical" },
  { key: "Minor Service", label: "Minor Service" },
  { key: "New Tyres", label: "New Tyres" },
  { key: "Oils", label: "Oils" },
  { key: "Order Tyres", label: "Order Tyres" },
  { key: "Parts", label: "Parts" },
  { key: "Remove old tyres", label: "Remove old tyres" },
  { key: "Repair", label: "Repair" },
  { key: "rim", label: "rim" },
  { key: "Road Worthy", label: "Road Worthy" },
  { key: "Rotation", label: "Rotation" },
  { key: "second hand tyres", label: "second hand tyres" },
  { key: "Strip & Fit Tyres", label: "Strip & Fit Tyres" },
  { key: "Supply Tube", label: "Supply Tube" },
  { key: "Suspension & Shock Absorbers", label: "Suspension & Shock Absorbers" },
  { key: "Wheel Alignment", label: "Wheel Alignment" },
  { key: "Wheel Ballance", label: "Wheel Ballance" },
  { key: "Windscreen", label: "Windscreen" }
]

export const mechanics = [
  { key: "Arden Connell", label: "Arden Connell" },
  { key: "Brett Minahan", label: "Brett Minahan" },
  { key: "David Smith", label: "David Smith" },
  { key: "Kieran Smith", label: "Kieran Smith" },
  { key: "Leonie", label: "Leonie" },
  { key: "Troy", label: "Troy" },
]